openapi: 3.0.1
info:
  title: V1 API General
  version: v1
components:
  schemas:
    BuyItemError:
      type: object
      properties:
        message:
          type: string
          nullable: true
      additionalProperties: false
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
