extends: .spectral.yaml
documentationUrl: https://gsoftdev.atlassian.net/wiki/spaces/TEC/pages/3858235678/IDP+OpenAPI+Rulesets
rules:
  must-accept-content-types:
    description: "All endpoint bodies MUST accept the header with (one of) Content-Type: application/json, multipart/form-data, application/octet-stream."
    message: "{{description}}"
    severity: warn
    given: $.paths[*].*.requestBody.content
    then:
      field: "@key"
      function: enumeration
      functionOptions:
        values:
          -  application/json
          -  multipart/form-data
          -  application/octet-stream

  must-return-content-types:
    description: "Endpoint bodies for 200 responses MUST return the header with (one of) Content-Type: application/json, image/png, application/octet-stream."
    message: "{{description}}"
    severity: warn
    given: $.paths[*].*.responses['200'].content
    then:
      field: "@key"
      function: enumeration
      functionOptions:
        values:
          -  application/json
          -  image/png
          -  application/octet-stream

  must-support-client-credentials-oauth2:
    description: "Contract must support client credentials with oauth2."
    recommended: true
    severity: warn
    given: $.components.securitySchemes.*
    then:
      field: type
      function: enumeration
      functionOptions:
        values:
          - oauth2
