openapi: 3.0.1
info:
  title: V1 API General
  version: v1
paths:
  /buy-item:
    post:
      tags:
        - Shop
      summary: Buy an item
      operationId: BuyItem
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                required:
                  - itemName
                type: object
