openapi: 3.0.1
info:
  title: V1 API General
  version: v1
components:
  schemas:
    BuyItem/Error:
      type: object
      properties:
        message:
          type: string
          nullable: true
      additionalProperties: false
