name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    paths-ignore: ["*.md"]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./test.ps1
        shell: pwsh